### ISSUE TITLE
Missing R groups

### ISSUE THREAD

**Issue by llrs** [benubah/r-community-explorer#12]
Great resource! Many thanks for maintaining it! I think the current community explorer misses some R user groups like this one: https://www.meetup.com/BarcelonaR/. 

I'm not sure because it has the r-project-for-statistical-computing topic. The map on the shiny dashboard doesn't show as many meetups as the [one shown on the topic](https://www.meetup.com/topics/r-project-for-statistical-computing/).

**Comment by benubah** [comment]
thanks!
I could try to possibly tweak the filter to let BarcelonaR come in.

Not sure what you mean about "_The map on the shiny dashboard doesn't show as many meetups as the one shown on the topic._" Really helps if you clarify, I added two screenshots below. I know more **R-specific groups** could be added and there could some **general data science groups** that could be removed.
![image](https://user-images.githubusercontent.com/11357251/118703415-f934ba00-b80d-11eb-8e70-f427c8949287.png)

![image](https://user-images.githubusercontent.com/11357251/118703533-1c5f6980-b80e-11eb-9921-5c41e0bec02f.png)

**Comment by llrs** [comment]
Sorry adding now the screenshot. As you can see on Barcelona it only appears the R-ladies but not the BarcelonaR User group I linked. 
![Screenshot from 2021-05-18 22-53-41](https://user-images.githubusercontent.com/6818218/118722054-f1840e00-b82b-11eb-8590-fc82be7db933.png)

I think it is good to show other more general groups.

**Comment by benubah** [comment]
The missing group is actually there. The problem is that for the map, four groups in Barcelona have the same lat/lon and that's why only one is visible. But in the datatable below, you can search for and find BarcelonaR.

If you view the [cluster map](https://benubah.github.io/r-community-explorer/rugs-cluster-map.html), you'll see this clearly:

![image](https://user-images.githubusercontent.com/11357251/121971834-96353500-cd71-11eb-9450-1a10b0105bd7.png)

**Comment by llrs** [comment]
Oh didn't knew about the cluster map, but now I see the option on the top right corner. Thanks for following up. 

Perhaps a note on the default map explaining that some groups might overlap would be helpful to avoid this kind of misunderstandings. 

Closing the issue then as the group(s) is not really missing
