### ISSUE TITLE
R en Buenos Aires missing?

### ISSUE THREAD

**Issue by eliocamp** [benubah/r-community-explorer#3]
Hi! I love the map but was wondering why our group R en Buenos Aires was missing and if it's possible to add it. We've got a [meetup page](https://www.meetup.com/renbaires/) and are active active (3 events this year).

**Comment by benubah** [comment]
Thanks!

It is not really missing. What I think is that R-Ladies Buenos Aires and R en Buenos Aires share the same latitude and longitude, so one marker (R-Ladies) is overlaid on the other. A solution is provided using Clustering - you can click "View Cluster Map" at the top right of the map you are looking at and then be able to find the marker for R e Buenos Aires.
![image](https://user-images.githubusercontent.com/11357251/64559008-2f355180-d33d-11e9-9f02-549def4b134b.png)


See screenshots below of cluster map.
![image](https://user-images.githubusercontent.com/11357251/64558936-00b77680-d33d-11e9-8a30-8e43af6a19a0.png)

And Datatable
![image](https://user-images.githubusercontent.com/11357251/64558663-50e20900-d33c-11e9-84f0-915bfde8ec1f.png)

**Comment by eliocamp** [comment]
Ah, I see. It was user error :laughing: 
Thanks again!

**Comment by benubah** [comment]
Is there anyway you would want  us to indicate this on the main dashboard so that other affected groups could find their way?

**Comment by eliocamp** [comment]
I've never worked with these types of maps so I wouldn't know. My first though would be to add a bit of jitter to the data to alleviate overplotting? Maybe

**Comment by benubah** [comment]
Thank you. I was actually thinking of some kind of way to direct other affected groups to the Cluster map when they view the dashboard and can't find their groups on the main map. Hoping to hear from a user's perspective.
