### ISSUE TITLE
pluralize "Average Member Per Group", "Average Event Per Group"

### ISSUE THREAD

**Issue by RickPack** [benubah/r-community-explorer#6]
Suggest replacing "Average Member Per Group" and "Average Event Per Group" with: 
"Average Members Per Group" and "Average Events Per Group"

This is a minor issue.

**Comment by benubah** [comment]
Done! Thanks!
https://github.com/benubah/r-community-explorer/commit/dcca212d548dad0ce0658beb31ea9745b2711721
