### ISSUE TITLE
Add status to interactive table in R-Ladies Dashboard

### ISSUE THREAD

**Issue by cvitolo** [benubah/r-community-explorer#8]
If there is any further development planned, it would be great if the chapter status (active, inactive, unbegan) and the date of the last event could be added to the interactive table in the R-Ladies Dashboard.

Chapter activity is something I check regularly. At the moment I query the meetup API. However, if the functionality gets built into the dashboard, that would be very handy.

**Comment by benubah** [comment]
Thanks! this is similar to https://github.com/benubah/r-community-explorer/issues/4
Since this is needed, I'll build this is in quickly to assist with your work.

**Comment by benubah** [comment]
Please you may check the dashboard now.

**Comment by cvitolo** [comment]
Looks wonderful, many thanks @benubah!

**Comment by cvitolo** [comment]
I noticed that 'Unbegan' chapters have the 'last event date' set to 1970-01-01, could this be changed to NA?

**Comment by benubah** [comment]
Will try....

**Comment by benubah** [comment]
Added now!
