### ISSUE TITLE
Count of R-Ladies is not correct

### ISSUE THREAD

**Issue by cvitolo** [benubah/r-community-explorer#9]
Hi @benubah!

Just reporting that in the R-Ladies dashboard, the count of cities is incorrect.

Current count is chapters = 188 and cities = 185, however this should be 188. 

This is because there are 2 chapters in:
- San Francisco, however one is a remote chapter and should be classified as having worldwide coverage.
- London, there are two cities with the same name (one in UK and one in Canada).
- Oxford, there are two cities with the same name (one in UK and one in USA).

The easiest fix, in my opinion, is to remove the city count as it is redundant (if correct, it should be equal to the number of chapters).

**Comment by benubah** [comment]
Thanks for pointing this out. Should I make the city count equal to chapter count or just remove it completely.?

**Comment by cvitolo** [comment]
I would simply remove it.

**Comment by benubah** [comment]
Removed!
